[2023-05-02T06:00:59.873+0000] {taskinstance.py:1084} INFO - Dependencies not met for <TaskInstance: user_processing.is_api_available scheduled__2023-05-01T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2023-05-02T06:00:59.888+0000] {local_task_job.py:151} INFO - Task is not able to be run
